### ISSUE TITLE
Error _sbrk if use sprintf, atof etc

### ISSUE THREAD

**Issue by sofwarestore** [maxgerhardt/pio-gd32f103#1]
If i use sprintf to convert variable to chart i get this error
 

c:/users/anonim/.platformio/packages/toolchain-gccarmnoneeabi@1.70201.0/bin/../lib/gcc/arm-none-eabi/7.2.1/../../../../arm-none-eabi/lib/thumb/v7-m\libc.a(lib_a-sbrkr.o): In function `_sbrk_r':
sbrkr.c:(.text._sbrk_r+0xc): undefined reference to `_sbrk'

Is there any solution for this error sir?

**Comment by maxgerhardt** [comment]
Can you please test the fix as done in https://github.com/maxgerhardt/pio-gd32f103/commit/ac493d66b12fe94c4159c91e3ed8e0e10cd6ac89? 

Otherwise I also have a few more ideas if it does not execute properly.. Problem may be in the linkerfile and the C library.

**Comment by sofwarestore** [comment]
Ok thanks..
I have test and it's work...
Thank's sir
