### ISSUE TITLE
get error in linux mint

### ISSUE THREAD

**Issue by sofwarestore** [maxgerhardt/pio-gd32f103#2]
hello sir..
i use linux mint as my operating system
i try this example i got error "'arm-none-eabi-as: unrecognized option '-x' "

before i use in windows it's use toolchain-gccarmnoneeabi@1.70201.0 as toochain and it's work
but in linux mint it use toolchain-gccarmnoneeabi without version

**Comment by maxgerhardt** [comment]
Per https://bintray.com/platformio/tool-packages/toolchain-gccarmnoneeabi-linux_x86_64#files Linux-x86-64 has the same toolchain version available.

Are you sure your PlatformIO core and platforms are up-to-date? (Open a [PIO CLI](https://docs.platformio.org/en/latest/integration/ide/vscode.html#platformio-core-cli) and do `pio upgrade` and `pio platform update`).

If that does not help try modifying this section of the `platformio.ini`

https://github.com/maxgerhardt/pio-gd32f103/blob/ac493d66b12fe94c4159c91e3ed8e0e10cd6ac89/platformio.ini#L11-L14

to

```
[env]
; globally override framework-spl for all environments.
platform_packages = 
    maxgerhardt/framework-spl@2.10300.0
    toolchain-gccarmnoneeabi@1.70201.0
```
and retry building.

**Comment by sofwarestore** [comment]
i try replace the toolchain and edit in platformio.ini 

but it's still error

Processing gd32f103rc (platform: ststm32; board: gd32f103rc; framework: spl)
-------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/ststm32/gd32f103rc.html
PLATFORM: ST STM32 (11.0.0) > Generic GD32F103RCT6
HARDWARE: GD32F103RCT6 108MHz, 48KB RAM, 256KB Flash
DEBUG: Current (stlink) On-board (stlink) External (blackmagic, jlink)
PACKAGES: 
 - framework-spl 2.10300.0 (1.3.0) 
 - toolchain-gccarmnoneeabi 1.70201.0 (7.2.1)
Warning! Cannot find a linker script for the required board! Firmware will be linked with a default linker script!
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 0 compatible libraries
Scanning dependencies...
No dependencies
Building in release mode
Compiling .pio/build/gd32f103rc/FrameworkCMSISVariant/startup_gd32f10x.o
arm-none-eabi-as: unrecognized option '-x'
Compiling .pio/build/gd32f103rc/FrameworkCMSISVariant/system_gd32f10x.o
*** [.pio/build/gd32f103rc/FrameworkCMSISVariant/startup_gd32f10x.o] Error 1

**Comment by maxgerhardt** [comment]
Okay, I'll test this tomorrow in a VM with Linux Mint.There could be another potential error. You can try and search for that system_gd33f10x file within ~/.platformio/packages, somewhere in the framework-spl folder.The file extension should be either .s or .S. Try renaming the file extension to the opposite case, aka .S or .s. Then clean and rebuild the project.(This is because Windows is case-insensite and can't tell the difference between abc.s and abc.S and maybe it invokes different compilers / assemblers for .s and .S files on Linux where it does have a case-sensitive filesystem)

**Comment by sofwarestore** [comment]
thank's you sir
it's solve by rename the extension .s to .S 
there's no anymore error

**Comment by maxgerhardt** [comment]
Okay good, I will republish the `framework-spl` then with a new version soon that has this error fixed.
